spring:
  application:
    name: customer-service

  config:
    # si el servidor no esta disponible, arranca igual
    import: "optional:configserver:"

  cloud:
    config:
      # direccion del config service
      uri: http://localhost:8888

