spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
